version: '3.9'

services:
  samba:
    image: dperson/samba
    container_name: samba-server
    restart: always
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - /media/exthdd2tb:/shared:rw
    environment:
      - USERID=1000
      - GROUPID=1000
      - TZ=Europe/Moscow
    command: >
      -u "ubuntu;rustam2810"
      -s "Shared;/shared;yes;no;no;all;none"
