---
- name: Install and Configure Java 17
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 86400
      ignore_errors: yes

    - name: Install OpenJDK 17
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present

    - name: Set JAVA_HOME environment variable for ARM64
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME="/usr/lib/jvm/java-17-openjdk-arm64"'
        create: yes
      when: ansible_architecture == "aarch64"

    - name: Verify Java Installation
      command: java -version
      register: java_version
      changed_when: false

    - name: Show Java version
      ansible.builtin.debug:
        var: java_version.stderr
