version: "3"
services:
  clickhouse1:
    image: yandex/clickhouse-server
    ports:
      - "10123:8123"
    restart: always
    networks:
      - click
  clickhouse2:
    image: yandex/clickhouse-server
    ports:
      - "10124:8123"
    restart: always
    networks:
      - click
  nginx:
    image: "nginx:1.17"
    ports:
      - "10090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - clickhouse1
      - clickhouse2
    links:
      - clickhouse1
      - clickhouse2
    networks:
      - click
networks:
  click:
    driver: bridge
