[Definition]
failregex = ^<HOST> - - .* "(?:LEAKIX|CONNECT|TRACE|TRACK|PROPFIND|PRI)(?:\s|").*$
            ^<HOST> - - .* "\S+ /[^"]*(?:\.env|\.git(?:/|$)|\.DS_Store|server-status|ecp/|owa/|autodiscover/|v2/_catalog|telescope/|actuator/|console/|login\.action|SDK/webLanguage|HNAP1|boaform/|cgi-bin/|phpmyadmin|pma/|adminer|wp-admin|wp-login\.php|wp-content|wordpress|xmlrpc\.php|vendor/phpunit|solr/|jenkins/|manager/html|geoserver|_profiler|debug/|___proxy_subdomain_)[^"]*" .*

ignoreregex = ^<HOST> - - .* "\S+ /\.well-known/acme-challenge/
