[Definition]
failregex = ^<HOST> - - .* "(?:LEAKIX|CONNECT|TRACE|TRACK|PROPFIND|PRI)(?:\s|").*$
            ^<HOST> - - .* "\S+ /[^"]*(?:\.env|\.git(?:/|$)|\.DS_Store|server-status|ecp/|owa/|autodiscover/|v2/_catalog|telescope/|actuator/|console/|login\.action|SDK/webLanguage|HNAP1|GponForm|boaform/|cgi-bin/|phpmyadmin|pma/|adminer|wp-admin|wp-login\.php|wp-content|wordpress|xmlrpc\.php|vendor/phpunit|solr/|jenkins/|manager/html|geoserver|_profiler|debug/|rpc/|developmentserver/metadatauploader|nice%%20ports|hello\.world|modx\.zip|joomla\.zip|wp\.zip|wp-admin\.zip|___proxy_subdomain_)[^"]*" .*
            ^<HOST> - - .* "\S+ [^"]*" 444 \d+ .*

ignoreregex = ^<HOST> - - .* "\S+ /\.well-known/acme-challenge/
