---
version: "2.1"
services:
  transmission:
    build:
      context: ./
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - USER=zen
      - PASS=rustam2810
    volumes:
      - /media/exthdd2tb/share/transmission/config:/config
      - /media/exthdd2tb/share/transmission/downloads:/downloads
      - /media/exthdd2tb/share/transmission/watch:/watch
    ports:
      - "8200:9091"
      - "51413:51413/tcp"
      - "51413:51413/udp"
    restart: always