---
- name: Install monitoring tools
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      ignore_errors: yes

    - name: Install lm-sensors
      ansible.builtin.apt:
        name: lm-sensors
        state: present
      ignore_errors: yes

    - name: Install hddtemp
      ansible.builtin.apt:
        name: hddtemp
        state: present
      ignore_errors: yes

    - name: Install sysstat (for iostat, mpstat)
      ansible.builtin.apt:
        name: sysstat
        state: present
      ignore_errors: yes

    - name: Detect available sensors
      ansible.builtin.shell:
        cmd: sensors-detect --auto
      become: yes
      args:
        creates: "/etc/sensors3.conf"
      ignore_errors: yes

    - name: Display CPU temperature using sensors
      ansible.builtin.command:
        cmd: sensors
      register: sensors_output
      changed_when: False
      ignore_errors: yes

    - name: Display sensors output
      ansible.builtin.debug:
        msg: "{{ sensors_output.stdout_lines }}"
      ignore_errors: yes
